UI dark mode
Project-Sustain/aperture-client pull request #170
Opened 2021-03-05 20:01 UTC by honeybadgerofdoom

2021-03-05 23:10 UTC, pierce-smith1 commented on src/iframe/css/main.css
> +.bs-tooltip-auto[x-placement^=top] .arrow::before,.bs-tooltip-top .arrow::before {
This is by far the most insane css selector I have ever seen

2021-03-05 23:13 UTC, pierce-smith1 commented on src/iframe/js/frame-specific/switchImageSources.js
> +		for(var i = 0; i < dropdownArrow.length; i++) {
Prefer `let` instead of `var` and `.forEach` instead of counting for loops

2021-03-05 23:17 UTC, pierce-smith1 commented
Looks good overall, but I am running into a bug where the dropdown arrows on dark mode are rending as boxes, and the local server is spitting 404s for `/images/DropdownWhite.png` (was this supposed to be `DropdownWhite.svg`)?
![image](https://user-images.githubusercontent.com/50504215/110184914-3a502d00-7dce-11eb-86a3-951d5d38a3b8.png)
![image](https://user-images.githubusercontent.com/50504215/110184928-42a86800-7dce-11eb-9b5c-fc6d589febda.png)

2021-03-05 23:18 UTC, pierce-smith1 requested changes
See previous comments

2021-03-06 15:32 UTC, honeybadgerofdoom commented on src/iframe/css/main.css
> +.bs-tooltip-auto[x-placement^=top] .arrow::before,.bs-tooltip-top .arrow::before {
haha yeah you get into some weird css when overriding Bootstrap source

2021-03-06 15:32 UTC, honeybadgerofdoom commented on src/iframe/js/frame-specific/switchImageSources.js
> +		for(var i = 0; i < dropdownArrow.length; i++) {
Noted, will update

2021-03-06 16:48 UTC, honeybadgerofdoom commented
Added the mysteriously missing image, updated loops to .forEach, updated 'var' to 'let'

2021-03-06 22:15 UTC, pierce-smith1 approved these changes
Works™

2021-03-09 01:10 UTC, drg101 approved these changes
Works for me!

2021-03-09 16:54 UTC, merged