Use IndexedDB & Add Zoom Restriction Option
Project-Sustain/aperture-client pull request #172
Opened 2021-03-09 17:33 UTC by drg101

Use IndexedDB, with the Dexie wrapper, to cache shapefiles. Advantages being:
- Doesn't use JS heap at all.
- The cached data will stay on the User's machine through reloads.

Also added ability to restrict zoom levels. Look at static attributes of `AutoQuery`. I've added a `DEV` boolean to map2.js where we set those zoom things to a less restricted amount.

2021-03-10 00:54 UTC, drg101 commented
Gonna add the aggregation thingy

2021-03-10 06:47 UTC, Marc-9 requested changes
Errors with Auto generated constraints
Electrical Substations- Uncaught TypeError: feature.properties is undefined
Power Plants/Hospitals- Uncaught Error: Invalid GeoJSON object.
Gas Pipelines- Uncaught TypeError: feature.properties is undefin in aperture util
Pretty much all the other also spam the console with invalid geojson object

2021-03-10 06:47 UTC, Marc-9 commented on src/iframe/js/frame-specific/map2.js
> +const DEV = true;
Wouldn't it be better to parse the domain url and check
Something like
const DEV = window.location.href.split("/")[1] === "dev"

2021-03-10 17:11 UTC, drg101 commented on src/iframe/js/frame-specific/map2.js
> +const DEV = true;
Yea, good idea

2021-03-10 17:20 UTC, drg101 commented
@Marc-9 addressed all of your issues

2021-03-10 21:40 UTC, drg101 commented
Going to add preloading

2021-03-11 03:31 UTC, drg101 commented
This thing is crazy fast now.

2021-03-11 04:01 UTC, Marc-9 approved these changes
Graph does not work, perhaps this will be fixed when merged
Also small css issue with the menu on screens <= 13 inches

2021-03-11 05:05 UTC, pierce-smith1 commented
Is zooming out supposed to be blocked in DEV mode? Because it doesn't seem to be.
Also, where is the preload status text showing up (is it supposed to show up at all?)

2021-03-11 05:15 UTC, pierce-smith1 commented
No idea why charting doesn't work because the code that deals with it hasn't changed, but we're going to have to deal with this problem regardless once the complete charting feature gets merged into dev. Boy, that's going to be fun.

2021-03-11 17:33 UTC, drg101 commented
@pierce-smith1 
> Is zooming out supposed to be blocked in DEV mode? Because it doesn't seem to be.
> Also, where is the preload status text showing up (is it supposed to show up at all?)
Zooming is unrestricted in DEV mode. The queries are honestly fast enough to zoom out a ton now anyways. 



> No idea why charting doesn't work because the code that deals with it hasn't changed, but we're going to have to deal with this problem regardless once the complete charting feature gets merged into dev. Boy, that's going to be fun.

All the data still goes through renderInfrastructure's renderGeoJson method, so that's weird. Which attributes are you pulling from the data, I've filtered the response data to only include what is going to be on the popup, which is likely your issue.

2021-03-11 17:34 UTC, drg101 commented
> Graph does not work, perhaps this will be fixed when merged
> Also small css issue with the menu on screens <= 13 inches

@honeybadgerofdoom Could you address the skinny menu issue in a separate PR?

2021-03-11 20:38 UTC, merged