Qualified feature names
Project-Sustain/aperture-client pull request #238
Opened 2021-03-22 06:47 UTC by pierce-smith1

Lots of internal changes that amount to the following things:
- Charts can now tell the difference between identically named constraints, i.e. things like SVI county and SVI tract are now separately plottable and will not be confused with one another.
- Human-readable names are now much easier to get (Closes #212).
- Scatterplots are now actually meaningful (guess what? Data coming into the scatterplots previously wasn't being joined on _anything_, meaning the distribution of data was effectively random. They are now properly joined by GISJOIN.)

Charting _may_ be noticeably slower with these changes, especially scatterplots.

2021-03-22 14:30 UTC, honeybadgerofdoom requested changes
Getting this error in the console when trying to change the x-axis or y-axis (scatterplots) via dropdown or toggles

scatterplotManager.js:132 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at scatterplotManager.js:132
    at Array.forEach (<anonymous>)
    at ScatterplotManager.prepareData (scatterplotManager.js:129)
    at ScatterplotManager.update (scatterplotManager.js:115)
    at chartSystem.js:139
    at Array.forEach (<anonymous>)
    at ChartSystem.update (chartSystem.js:139)

2021-03-22 15:20 UTC, drg101 commented
Same error for me on Chrome. Everything else looks super nice though.

2021-03-22 20:27 UTC, pierce-smith1 commented
Wouldn't you know it, this happens when you try to plot county vs. tract data because it can't join them together. For now I'll have this branch just disallow this type of plot and we'll figure out how this works with the UI later.

2021-03-22 20:34 UTC, pierce-smith1 commented
Scatterplots that try to mix county and tract data should now errorlessly self-destruct.

2021-03-23 00:42 UTC, drg101 commented
New error now: 
```
Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at ScatterplotManager.prepareData (scatterplotManager.js:127)
    at ScatterplotManager.update (scatterplotManager.js:115)
    at chartSystem.js:139
    at Array.forEach (<anonymous>)
    at ChartSystem.update (chartSystem.js:139)
```

2021-03-23 00:43 UTC, drg101 commented
^ this happened when I tried to plot svi tract vs household income tract.

2021-03-23 00:45 UTC, drg101 requested changes
See above

2021-03-23 02:16 UTC, pierce-smith1 commented
I can't reliably reproduce this problem, but based on the error that's being thrown, this should fix it.

2021-03-23 14:39 UTC, drg101 commented on src/iframe/js/library/charting/scatterplotManager.js
> +                    x: xfeat.find(d => d.GISJOIN === gisjoin).data,
Would be faster to do `xEntry.data` and `yEntry.data` so it doesn't have to do `.find` more times.

2021-03-23 22:30 UTC, pierce-smith1 commented on src/iframe/js/library/charting/scatterplotManager.js
> +                    x: xfeat.find(d => d.GISJOIN === gisjoin).data,
Not sure how I didn't catch that, but it's changed now

2021-03-25 16:47 UTC, drg101 approved these changes
Good

2021-03-25 22:58 UTC, honeybadgerofdoom approved these changes
Looks good!

2021-03-25 22:59 UTC, merged