Webpack
Project-Sustain/aperture-client pull request #250
Opened 2021-04-01 05:23 UTC by drg101

2021-04-01 08:42 UTC, pierce-smith1 commented
![image](https://user-images.githubusercontent.com/50504215/113267649-d406df00-9293-11eb-94e7-5c9f9a8bba6a.png)
Developing locally - I have a hunch this isn't supposed to happen

2021-04-01 08:44 UTC, pierce-smith1 commented
Tried to run an npm update, got this:
![image](https://user-images.githubusercontent.com/50504215/113267969-234d0f80-9294-11eb-811d-1e896916cb92.png)

2021-04-01 17:21 UTC, drg101 commented
@pierce-smith1 Can you try removing your `node_module` dir and doing `npm i`

2021-04-02 06:19 UTC, pierce-smith1 requested changes
The site seems to throw 404 errors for "/[object%20Module]" when trying to render icons on the map, e.g. for electrical substations. Given the "Module" this seems to be a webpack issue not dealing with images properly - not sure how to resolve this issue yet.

2021-04-03 03:57 UTC, pierce-smith1 approved these changes
Unable to find any more problems.

2021-04-03 03:58 UTC, pierce-smith1 commented on README.md
> +            /frame-specific    # js that is specific to a certain frame
That being said, this folder doesn't exist anymore so it should probably be taken out of the readme

2021-04-06 17:03 UTC, merged