Reimplement covid line tooltips
Project-Sustain/aperture-client pull request #362
Opened 2021-06-29 05:43 UTC by pierce-smith1

Returns the old functionality where you could hover over lines in the COVID chart to see what county there were a part of.

The Rnd component made this an _absolutely colossal_ pain, for more reasons than one. Please test thoroughly, as this fix definitely involves some really hacky duct-tape solutions.

Closes #361.

2021-06-29 16:32 UTC, drg101 requested changes
A few things:
The hover-over seems inaccurate, watch this video:
https://streamable.com/cn3azk

The [cursor](w3schools.com/cssref/pr_class_cursor.asp) shouldn't be a "move" cursor whenever mousing over the graphs. Maybe we should implement it like windows and only allow the moving to be done on the header.

The tooltip seems to be a fixed distance from the cursor up-and-to-the-left. This means it disappears if you go too far to the left side of the graph, or too far up.

On a separate note, should the hover give the value of the y and x-axis too? This will probably be a pain to implement, but it is needed to match most pre-built charting framworks.

2021-06-29 16:32 UTC, drg101 commented on src/js/ui/NewCharting/ChartingResizable.js
> +                    setPos({ x: x.x, y: x.y });
Legendary piece of code right here.

2021-06-29 20:18 UTC, pierce-smith1 commented
> The hover-over seems inaccurate, watch this video:
Unfortunately, what I'm seeing in that video is the cursor transformation that took so much effort to make not working... I have to wonder if it's a cross-browser thing, since I haven't tested it yet outside FF. (I'll do that soon)

> The cursor shouldn't be a "move" cursor whenever mousing over the graphs. 
I agree, and I _think_ this can be somewhat easily fixed by some Rnd props.

> The tooltip seems to be a fixed distance from the cursor up-and-to-the-left. 
It's supposed to be right above the cursor, and there is logic to bump it leftwards when you get too close to the right side - it just looks very bad on your end because the cursor transform isn't working. (There is no logic to bump it downwards if it gets too close to the top, but this tends to be a non-issue since the graph very rarely goes that high)

> should the hover give the value of the y and x-axis too?
Yes. 

> This will probably be a pain to implement
Possibly, but not necessarily - I will give it a try in this branch. The hard part of this PR was programmatically locating the cursor between all the breaking crap that Rnd does, drawing new stuff should be (relatively) simple.

2021-06-29 22:43 UTC, pierce-smith1 commented
@drg101 This should take care of the big issues - adding more details to the pop-up will be done later in the more general fashion we can re-use for other graphs.
There are two CC issues, but they're somehow not related to the line chart at all, and refactoring to fix them would be fairly complicated and outside the scope of this PR.

2021-06-30 16:53 UTC, drg101 commented
All seems to work.

2021-06-30 16:53 UTC, drg101 approved these changes

2021-06-30 16:53 UTC, merged