Faster Rendering and Color Changing
Project-Sustain/aperture-client pull request #373
Opened 2021-08-03 05:39 UTC by drg101

2021-08-05 02:11 UTC, pierce-smith1 requested changes
I never thought I would see the day the client was _this_ fast. Will approve when you address the missing license, fix the tests and address CC.

2021-08-05 02:11 UTC, pierce-smith1 commented on src/js/library/renderInfrastructure.js
> +        geoJsonData.properties.apertureName = iconName;
This is causing a test failure - the mock `geoJsonData` object provided by the tests does not have a `.properties.`

2021-08-07 17:41 UTC, drg101 commented
- Sped up rendering on a general level
- Very fast color switching
- Added an intersection switch onto the data exploration tab. This will make tracts and counties only display if they have fit ALL of the collections, and their corresponding fields/constraints. 
- Known issue/thing: when the intersection tab is on, rendering is a bit clunky, especially with tracts. This is because it is nearly impossible to sync up the rendering processes without destroying speed.

2021-08-08 18:09 UTC, honeybadgerofdoom approved these changes
w0w so speedy! Looks good to me.

2021-08-09 17:09 UTC, drg101 commented
Hold up, found a bug.

2021-08-09 22:44 UTC, pierce-smith1 approved these changes
Hard to believe that this works so well.

One minor point is that we could definitely use a help tooltip or something alone those lines for the intersection button, since its use isn't super obvious from the name alone. (There also might be a better place for it in the UI)

2021-08-09 22:46 UTC, Marc-9 approved these changes
I thought I found a bug with turning on/off the intersection after adding a new layer but after not being able to recreate it I think the server just happened to go down for a moment in time, as the menu was not showing up for a while after reload.
It also appears that this will fix the multiple layers issue in graphing, so Id love to get this in asap so I may merge master into my branch again and get my PR up and running

2021-08-09 23:15 UTC, merged