Chart Fixes
Project-Sustain/aperture-client pull request #375
Opened 2021-08-06 03:28 UTC by Marc-9

temp pull request

2021-08-10 04:42 UTC, Marc-9 commented
Issues to resolve before merge
Delete issue- Talked with Matt about this, seems to be a key problem, all frames (graphs) are stored in an array and passed their index in the array, on delete the graph deletes itself from the array, however the graphs after it inherit their selected layer.
Add Delete button on covid date

To be fixed later
Sizing issues- Some graphs don't look great in the resizable this is a sizing issue hopefully Matt can look at
Box Plot ugliness- The box plot is pretty small for some layers but not for other, it also is missing its one of its lines

2021-08-10 21:23 UTC, pierce-smith1 requested changes
I'll approve this once the notes I placed on the code get resolved and the CC problems are either ignored or fixed (the d3 complaints about long functions can be ignored). There are more things we should take note of:

* Histogram bars are black sometimes when they are first created
![image](https://user-images.githubusercontent.com/50504215/128936536-7c3d12d7-4b33-4dbf-906a-6b3b9bb11781.png)

* Scatterplots show erroneous 0 entries for (what I'm assuming are) locations that don't both have data for a particular constraint (e.g. here, I'm looking at counties that don't have heatwave data but do have svi data, and the dots that don't have heatwave data are shoved into 0 degrees)
![image](https://user-images.githubusercontent.com/50504215/128936704-c3ac49d5-b63e-4438-858c-6373ebb853ef.png)

Note that this _only_ occurs when the dataset with missing entries on the y axis.


* The covid graph has lost its ability to hover over counties somehow (great)

* The correlogram still isn't working right? the diagonals should be 1.0 and the off-diagonals should be mirrored, but this correlogram:
![image](https://user-images.githubusercontent.com/50504215/128934884-211d7e25-6458-4387-aca0-5188c5580b04.png)
...looks like 
```
1.0   -0.063
-0.53 0.16
```
instead of something like
```
1.0   -0.53
-0.53 1.0 
```

Out of these the correlogram is really the highest priority, since if the graph is incorrect that's bad news. I can help with the histogram rendering issue and covid graph issue, since those are probably my fault anyway.

2021-08-10 21:23 UTC, pierce-smith1 commented on src/js/ui/NewCharting/ChartTemplates/CorrelogramGraph.js
> +                const correlation = calculateCorrelation(x, y);
This is causing a crash if a tract and county dataset are both enabled at a time while the correlogram is open.

To reproduce:
* enable a county dataset (i.e. heatwaves)
* open the correlogram 
* enable a tract dataset (i.e. tract svi)
* wait for death

2021-08-10 21:23 UTC, pierce-smith1 commented on src/js/ui/NewCharting/ChartTemplates/CorrelogramGraph.js
> +                keys.push(key.split("::")[2])
A few more `split`s to replace

2021-08-11 00:22 UTC, drg101 commented
![Screenshot 2021-08-10 6 17 25 PM](https://user-images.githubusercontent.com/37166660/128951098-2e30d343-f797-414d-acc0-d32282736cc7.png)

An issue with scatterplots when one collection has entries rendering which the other does not.

2021-08-11 00:32 UTC, drg101 commented
![Screenshot 2021-08-10 6 29 08 PM](https://user-images.githubusercontent.com/37166660/128951920-d18d391b-75b7-4b54-bdda-d670b102010f.png)
A lot of things going wrong in this screenshot. Weird data, console logs, console errors.

2021-08-11 01:07 UTC, pierce-smith1 commented
> +1 On all of pierce's reviews as well, but more than anything else, the whole graphing system feels "off."
> Here is a video of me trying to create a histogram. It doesn't seem to update in real-time anymore.
> https://streamable.com/vmfp4g
> 
> The system feels like this for every other graph as well.

This is very noticeable and as the person behind the original infrastructure I want to do some investigation into why it's happening. I really hope this isn't a problem with React.

2021-08-12 03:39 UTC, Marc-9 commented
Right now I believe I have fixed the scatterplot issue and correlogram, however I have only set up the correlogram to work with tracts, I reckon I could get them to work with counties but its less useful with less data, and I think Shrideep cares more if it works with the neon data.
I can fix the failing test issue next but as for the black bars and slow re-rendering not sure what I can do in this branch at least

2021-08-12 03:52 UTC, Marc-9 commented
I still have other things to work out but let me know if you see new things or if the issues I think I resolved were not really fixed

2021-08-12 21:34 UTC, pierce-smith1 commented
I am still seeing the scatterplot bug: 
![image](https://user-images.githubusercontent.com/50504215/129272701-2f6d6df2-64ef-4136-bbb9-6fd19dc0ab85.png)

The correlogram is doing better in terms of accuracy, but the bottom-left squares are completely black and have no value:
![image](https://user-images.githubusercontent.com/50504215/129272882-92e7c8c9-2845-4fde-a0b6-65c4261fed42.png)

This in console:
![image](https://user-images.githubusercontent.com/50504215/129273062-3de26a9b-7b25-45d3-a6bc-5dafdb617742.png)

Also, if you open the correlogram with nothing being rendered, the client crashes with this in console:
![image](https://user-images.githubusercontent.com/50504215/129273114-4c15bdb9-3eb8-4963-91d0-1d2f2d01a4aa.png)

2021-08-12 21:56 UTC, Marc-9 commented
@pierce-smith1 can you give me the location where this scatterplot issue is showing up
As for the bottom left in the correlogram, those are equivalent to the top right, so to save confusion they are just black

Ill work on the console bugs rn

2021-08-13 00:57 UTC, pierce-smith1 commented
> @pierce-smith1 can you give me the location where this scatterplot issue is showing up
> As for the bottom left in the correlogram, those are equivalent to the top right, so to save confusion they are just black
> 
> Ill work on the console bugs rn

Right in the middle of South Dakota is a region missing a lot of heatwave data, you can recreate the bug fairly reliably there.

I'd argue that making the lower left entries in the correlogram black and valueless is more confusing than just having them mirror across the diagonal, but maybe someone else can provide some input.

2021-08-13 21:41 UTC, Marc-9 commented
Here is what I believe we have left before merging
1. Correlogram should have no errors in console (but can look ugly atm)
2. Fix the key/indexing bug that causes deleted frames to have their properties inherited by the frame next in the array

I want to finish these today but if I cant get the menu to load it may be a bit later

2021-08-20 03:17 UTC, pierce-smith1 requested changes
The scatterplot bug is fixed, but the correlogram is now crashing when any data is all is enabled on the map:
![image](https://user-images.githubusercontent.com/50504215/130173502-088fd9f5-80bb-47f8-9c61-5c33aea7b2df.png)

Also, creating and deleting chart frames seems to have an extremely long delay. Unless you double-click them, it seems to take anywhere from a couple seconds to forever to actually create or delete the chart. I don't remember this behavior in previous commits of the branch.

2021-08-20 03:40 UTC, Marc-9 commented
> The scatterplot bug is fixed, but the correlogram is now crashing when any data is all is enabled on the map:
> ![image](https://user-images.githubusercontent.com/50504215/130173502-088fd9f5-80bb-47f8-9c61-5c33aea7b2df.png)
> 
> Also, creating and deleting chart frames seems to have an extremely long delay. Unless you double-click them, it seems to take anywhere from a couple seconds to forever to actually create or delete the chart. I don't remember this behavior in previous commits of the branch.

Yup sorry about that, uncommitted change fixed the correlogram
As for the delete issue, I don't see the same problem on my end, deletes are relatively quick (1-2 seconds)
But it did make me realize a bug in the way I handle graphs, which I will work on solving now, can anyone else see if deletes are causing issues

2021-08-22 22:45 UTC, drg101 approved these changes
No errors in the console, but everything still seems sluggish. We can talk about how to resolve this at the next meeting. For now though, this is an improvement.

2021-08-23 00:56 UTC, merged