Style charting
Project-Sustain/aperture-client pull request #393
Opened 2021-08-30 21:52 UTC by honeybadgerofdoom

I'm working on the merge conflict right now. This isn't totally done but this is the first 80% of styling. Doing this now so the branch isn't out for very long, will do another styling PR soon.

2021-08-30 22:25 UTC, honeybadgerofdoom commented
Looking at all of the console.log() error with Pierce, coming from Dependency issue

2021-08-31 03:09 UTC, honeybadgerofdoom commented
Styling is not done yet, want to get this branch in now so its not out for a super long time. Will finish up styling in next PR.

2021-08-31 03:48 UTC, drg101 commented on src/js/ui/NewCharting/ChartGlobalControls.js
> +                    <MenuItem onClick={() => {
This should be refactored, but this isn't really your responsibility. @Marc-9 @pierce-smith1 Think about making this based on some external object and using a map in a future PR.

2021-08-31 03:55 UTC, drg101 approved these changes
Looks very clean and is pretty easy to use. The switch for county/tracts is a bit confusing but that can be easily changed whenever.

2021-09-01 00:48 UTC, Marc-9 requested changes
The delete button disappears if the resizable is made to small, consider allowing the menu flow into the second line or increasing the minimum resizable width
Mac safari throws error in console on load
Warning: React does not recognize the `justifyContent` prop on a DOM element

The county and tract toggle button no longer works on correlogram and it seems to always default to county

2021-09-01 01:26 UTC, Marc-9 approved these changes
Thanks looks good

2021-09-01 01:43 UTC, honeybadgerofdoom commented on src/js/ui/NewCharting/ChartGlobalControls.js
> +                    <MenuItem onClick={() => {
@drg101 did a quick refactor here

2021-09-01 01:44 UTC, merged