Saving & Loading Improvements + Share Button & More
Project-Sustain/aperture-client pull request #406
Opened 2021-09-08 01:49 UTC by drg101

2021-09-08 01:55 UTC, drg101 commented
Yes I know the styling is bad, @honeybadgerofdoom Plz fix the styling on `Save.js`, `Load.js`, `Share.js`, `SaveAndLoadAndShare.js`, and `SavedWorkspaceSlotSelection.js` once this is merged.

- Added menus for saving, loading, & sharing
- There is 10 slots to save with
- Color state gets saved now. **Known bug: The saved/loaded color of intersected tracts/counties is inconsistent**

The live site (which is what the share link defaults to), doesn't support view port or color state right now, so you will just have to trust me on that for now OR add the `?workspace=<base64String>` into your localhost environment.

2021-09-08 01:57 UTC, drg101 commented
Please test the _functionality_ of this as well as you can. I threw this together pretty quick.

2021-09-08 23:26 UTC, pierce-smith1 commented on src/js/ui/NewDataExploration/Save.js
> +    if (componentIsRendering) { console.log("|Save Rerending|") }
Rogue log

2021-09-08 23:38 UTC, pierce-smith1 requested changes
I tried a lot of different things and it all seems to be working (nearly) flawlessly. Small issues:

* You can save a workspace with an empty name (it still works, but you probably shouldn't be able to do this)
* There are 9 slots instead of 10
* Several logs left behind in code

From a design standpoint, I can forsee some issues with saving workspaces in local storage. I don't know how permanent it is, but if there's a potential that it disappears without warning that could be a problem. Saving as files _may_ be a better alternative, depending on how reliable local storage is.

2021-09-08 23:38 UTC, pierce-smith1 commented on src/js/ui/NewDataExploration/Save.js
> +    if (componentIsRendering) { console.log("|Save Rerending|") }
Rogue log

2021-09-08 23:38 UTC, pierce-smith1 commented on src/js/ui/NewDataExploration/SaveAndLoadAndShare.js
> +    if (componentIsRendering) { console.log("|SaveAndLoad Rerending|") }
Ditto

2021-09-08 23:38 UTC, pierce-smith1 commented on src/js/ui/NewDataExploration/SavedWorkspaceSlotSelection.js
> +    if (componentIsRendering) { console.log("|Load Rerending|") }
Ditto

2021-09-08 23:38 UTC, pierce-smith1 commented on src/js/ui/NewDataExploration/Load.js
> +    if (componentIsRendering) { console.log("|Load Rerending|") }
Ditto

2021-09-09 01:30 UTC, drg101 commented
> I tried a lot of different things and it all seems to be working (nearly) flawlessly. Small issues:
> 
> * You can save a workspace with an empty name (it still works, but you probably shouldn't be able to do this)
> * There are 9 slots instead of 10
> * Several logs left behind in code
> 
> From a design standpoint, I can forsee some issues with saving workspaces in local storage. I don't know how permanent it is, but if there's a potential that it disappears without warning that could be a problem. Saving as files _may_ be a better alternative, depending on how reliable local storage is. (Admittedly, local storage is much easier and more intuitive to use than files)

- These logs don't show up during normal use, they are in all the workspace react files for when we want to see if they are rendering. The flag can be turned on in an external file.

- I'll add one more slot, thanks for pointing that out.

- Local storage should be fine for now, as it is only deleted if the [user wants it to be deleted](https://stackoverflow.com/questions/8537112/when-is-localstorage-cleared). Anyways, we will probably be transitioning this to using the API sometime in the future.

2021-09-09 01:58 UTC, pierce-smith1 approved these changes

2021-09-09 02:43 UTC, Marc-9 commented
Would you say the save workspace overlay would be under the purview of styling?
Atm on my Mac I cant save to anything other than the first 5 slots as the others are hidden beyond my screen, most likely would be solved by changing the default coords or doing an overflow:hidden
In fact I can not even save because it is hidden

2021-09-09 02:43 UTC, honeybadgerofdoom approved these changes
This is super duper cool. Will style it once it's merged.

2021-09-09 02:48 UTC, Marc-9 approved these changes
I don't know enough about local storage to know if there are some reserved names, but we may want to sanitize/limit the chars allowed for saving a name
Also perhaps a different button/disable the load workspace if no workspaces are saved

2021-09-09 02:51 UTC, pierce-smith1 commented
> I don't know enough about local storage to know if there are some reserved names, but we may want to sanitize/limit the chars allowed for saving a name

This shouldn't be a problem, since the workspace names are stored in the serialized JSON rather than keys in local storage. I tried a thousand-character long name and one with unicode characters and both worked.

2021-09-09 02:51 UTC, drg101 commented
> I don't know enough about local storage to know if there are some reserved names, but we may want to sanitize/limit the chars allowed for saving a name
> Also perhaps a different button/disable the load workspace if no workspaces are saved

Luckily the 'name' is contained within the serialized & compressed workspace data, and the workspaces are named `workspace<i>` where `i` is a number from 1 to 10.

2021-09-09 02:51 UTC, drg101 commented
> > I don't know enough about local storage to know if there are some reserved names, but we may want to sanitize/limit the chars allowed for saving a name
> 
> This shouldn't be a problem, since the workspace names are stored in the serialized JSON rather than keys in local storage. I tried a thousand-character long name and one with unicode characters and both worked.

+1

2021-09-09 02:51 UTC, drg101 commented
> Also perhaps a different button/disable the load workspace if no workspaces are saved

Good idea

2021-09-09 02:52 UTC, merged