Style Save/Load/Share
Project-Sustain/aperture-client pull request #411
Opened 2021-09-09 20:42 UTC by honeybadgerofdoom

This PR styles the save/load/share components. Open to suggestions as always.

2021-09-09 21:21 UTC, pierce-smith1 requested changes
Needless to say this is a _massive_ improvement. Some suggestions/comments:

Workspace names should be truncated if they are too long, otherwise it bleeds into the radio button and causes a nasty horizontal scroll to appear.
![image](https://user-images.githubusercontent.com/50504215/132762710-59491b87-b467-478c-b5dd-359a64b66278.png)

This is a nice indication of what should go into this box, but it also means that if they don't put anything down, the workspace gets saved as "Workspace Name..." rather than just being rejected.
![image](https://user-images.githubusercontent.com/50504215/132762956-c294383b-3ee2-41ce-900d-9b82f47ce10a.png)
On this topic as well: when a workspace save gets rejected due to a missing name, there should be some indication that is why the saving failed - right now, absolutely nothing happens.

This one could go either way. Personally I'm not a fan of the way that clicking in the text portion of the box automatically copies the whole link - what if I just want to copy part of the link? That being said, 99% of the time people just want to copy the whole thing and the current behavior makes that a lot easier. (I'm sure there's a good hour or two of possible UX discussion here so I'm happy to hear other thoughts)
![image](https://user-images.githubusercontent.com/50504215/132763230-82d7714c-f81c-4c6e-bac9-e3b40806b3de.png)

High screen DPIs/zoom levels cause this to get skewed off-center a bit - it may be possible to get better centering.
![image](https://user-images.githubusercontent.com/50504215/132764187-4500ee17-4873-4cd6-b1d1-394b1a6ae8ab.png)

2021-09-10 01:40 UTC, Marc-9 approved these changes
Nothing new from what Pierce said, I would like however to be able to select a workspace by clicking its row and not just by clicking the button.
Not necessary at all, I have no idea how easy/hard this would be

2021-09-10 03:37 UTC, drg101 commented
> Needless to say this is a _massive_ improvement. Some suggestions/comments:
> 
> Workspace names should be truncated if they are too long, otherwise it bleeds into the radio button and causes a nasty horizontal scroll to appear.
> ![image](https://user-images.githubusercontent.com/50504215/132762710-59491b87-b467-478c-b5dd-359a64b66278.png)
> 
> This is a nice indication of what should go into this box, but it also means that if they don't put anything down, the workspace gets saved as "Workspace Name..." rather than just being rejected.
> ![image](https://user-images.githubusercontent.com/50504215/132762956-c294383b-3ee2-41ce-900d-9b82f47ce10a.png)
> On this topic as well: when a workspace save gets rejected due to a missing name, there should be some indication that is why the saving failed - right now, absolutely nothing happens.
> 
> This one could go either way. Personally I'm not a fan of the way that clicking in the text portion of the box automatically copies the whole link - what if I just want to copy part of the link? That being said, 99% of the time people just want to copy the whole thing and the current behavior makes that a lot easier. (I'm sure there's a good hour or two of possible UX discussion here so I'm happy to hear other thoughts)
> ![image](https://user-images.githubusercontent.com/50504215/132763230-82d7714c-f81c-4c6e-bac9-e3b40806b3de.png)
> 
> High screen DPIs/zoom levels cause this to get skewed off-center a bit - it may be possible to get better centering.
> ![image](https://user-images.githubusercontent.com/50504215/132764187-4500ee17-4873-4cd6-b1d1-394b1a6ae8ab.png)

Thanks for doing this quick. I'm just gonna merge this and implement these bug fixes in my next PR since they are pretty minor.
@pierce-smith1 I think the whole text getting copied is fine since the only other thing people would want is the base URL, which will already be the URL in their browser.

2021-09-10 03:38 UTC, drg101 approved these changes

2021-09-10 03:38 UTC, merged