Confirm overwrite workspace
Project-Sustain/aperture-client pull request #422
Opened 2021-09-16 16:43 UTC by honeybadgerofdoom

This PR adds an alert asking users to confirm before they overwrite an existing workspace

2021-09-16 18:44 UTC, pierce-smith1 reviewed
Works:tm: beautifully, will approve once the CC issues are fixed. You can probably ignore the cognitive complexity one but the code duplication issues seem valid.
(On that note, why are we just now getting those two code duplication issues? Hasn't that code existed for a while)?

2021-09-16 18:45 UTC, drg101 commented on src/js/ui/NewDataExploration/Load.js
> +END OF TERMS AND CONDITIONS
Extra licence was inserted here for some reason.

2021-09-16 18:46 UTC, drg101 commented on src/js/ui/NewDataExploration/Load.js
> +                <SavedWorkspaceSlotSelection title="Select a Saved Workspace" setNameOfCurrentSlot={() => {}} slotCurrentlySelected={slotCurrentlySelected} setSlotCurrentlySelected={setSlotCurrentlyS
Why is setNameOfCurrentSlot just a empty function, should this be deleted?

2021-09-16 19:02 UTC, drg101 requested changes
A few things on the logic of how it is determined that a slot already has a name.
Right now, the `setNameOfCurrentSlot` is used to pass this up to the `Save` component. The `Save` component already has a reference to the current slot with `slotCurrentlySelected` though, so this other prop is redundant. 

Looks good other than this though, will approve once the state stuff is addressed.

2021-09-16 20:51 UTC, honeybadgerofdoom commented on src/js/ui/NewDataExploration/Load.js
> +                <SavedWorkspaceSlotSelection title="Select a Saved Workspace" setNameOfCurrentSlot={() => {}} slotCurrentlySelected={slotCurrentlySelected} setSlotCurrentlySelected={setSlotCurrentlyS
It needs to be there or SavedWorkspaceSlotSelection throws an error when called from Load.js.

2021-09-16 21:15 UTC, honeybadgerofdoom commented
> A few things on the logic of how it is determined that a slot already has a name.
> Right now, the `setNameOfCurrentSlot` is used to pass this up to the `Save` component. The `Save` component already has a reference to the current slot with `slotCurrentlySelected` though, so this other prop is redundant.
> 
> Looks good other than this though, will approve once the state stuff is addressed.

slotCurrentlySelected is an int. If I understand correctly it is used to index into a data structure that isn't visible in Save.js, so I created another piece of state to hold the name (or null) at that index. Not sure how I could use just this int to get the name of the selected slot, or if it is null.

2021-09-16 21:20 UTC, honeybadgerofdoom commented
> A few things on the logic of how it is determined that a slot already has a name.
> Right now, the `setNameOfCurrentSlot` is used to pass this up to the `Save` component. The `Save` component already has a reference to the current slot with `slotCurrentlySelected` though, so this other prop is redundant.
> 
> Looks good other than this though, will approve once the state stuff is addressed.

K I'll work on this, thanks!

2021-09-17 04:13 UTC, drg101 requested changes
One more thing, could "Empty Slot" be changed to something that makes more sense like "Saved Workspace" or something?

2021-09-17 13:57 UTC, merged