Clickable Charts
Project-Sustain/aperture-client pull request #598
Opened 2022-10-19 21:37 UTC by absarah

- Potentially implement a rerender to the top of the Analysis Panel when one of the lower charts are clicked (eg: Correlogram)
     - Avoid having to scroll to the top

2022-10-19 22:13 UTC, tmoleary21 requested changes
Works great! You're probably right that having it move the scroll back to the top would be ideal, but if you'd rather us look into that down the line, I don't see any issue with that. Once the box plot thing is fixed, ready to merge

2022-10-19 22:13 UTC, tmoleary21 commented on src/js/ui/dataAnalysis/Charting/ChartingPane.js
> +    const chartTypes = ["Histogram","BubblePlot","ScatterPlot","BoxPlot","Correlogram","Radar"];
This change to the BoxPlot name is good for consistency, but it causes the box plot to not render correctly. I think it should just be making the same change in the switch statement in Frame.js. Could you take a look at that?

2022-10-25 21:10 UTC, absarah commented on src/js/ui/dataAnalysis/Charting/ChartingPane.js
> +    const chartTypes = ["Histogram","BubblePlot","ScatterPlot","BoxPlot","Correlogram","Radar"];
Yes absolutely, I'll jump into Frame.js and correct that render issue. For consistency reasons, I'll work through that file to make the names consistent across the program.

2022-10-25 21:15 UTC, absarah commented on src/js/ui/dataAnalysis/Charting/ChartingPane.js
> +    const chartTypes = ["Histogram","BubblePlot","ScatterPlot","BoxPlot","Correlogram","Radar"];
I will also work on the rerender ability with a useEffect() to avoid extra work in the future. =)

2023-07-05 18:18 UTC, falarrieu approved these changes

2023-07-05 18:18 UTC, merged